---
title: "R Notebook"
output: html_notebook
---



```{r}
library(MASS)
library(ISLR)
lm.fit=lm(medv~lstat,data=Boston)
summary(lm.fit)
```
```{r}
plot(Boston$lstat,Boston$medv)
abline(lm.fit,lwd=3,col='red')
```

```{r}
par(mfrow=c(2,2))
plot(lm.fit)
plot(predict(lm.fit),residuals(lm.fit))
plot(predict(lm.fit),rstudent(lm.fit))
plot(hatvalues(lm.fit))
```

```{r}
lm.fit=lm(medv~lstat+age,data=Boston)
summary(lm.fit)
```


```{r}
lm.fit=lm(medv~.,data=Boston)
summary(lm.fit)
```
```{r}
lm.fit=lm(medv~.-age,data=Boston)
summary(lm.fit)
```

```{r}
summary(lm(medv~lstat*age,data=Boston))
```

```{r}
lm.fit = lm(medv~lstat+I(lstat^2),data=Boston)
summary(lm.fit)

```

```{r}
lm.fit2 = lm(medv~lstat,data=Boston)
anova(lm.fit,lm.fit2)
```

```{r}
lm.fit5= lm(medv~poly(lstat,5),data=Boston)
summary(lm.fit5)
```

```{r}
fix(Carseats)
names(Carseats)
```

```{r}
lm.fit = lm(Sales~.+Income:Advertising+Price:Age,data=Carseats)
summary(lm.fit)

```

```{r}
attach(Carseats)
contrasts(ShelveLoc)
```

